---
root: true

plugins:
  - functional

extends:
  - airbnb
  - 'plugin:react-hooks/recommended'


parserOptions:
  ecmaVersion: latest

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node

rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  no-console: ['error', { allow: ['warn', 'error'] }]
  import/extensions: 'off'
  react/prop-types: 'off'
  functional/no-conditional-statement: 'off'
  functional/no-expression-statement: 'off'
  functional/immutable-data: 'off'
  functional/functional-parameters: 'off'
  functional/no-try-statement: 'off'
  functional/no-throw-statement: 'off'
  jsx-a11y/label-has-associated-control: 'off'